server:
  port: 8080
spring:
  application:
    name: demo
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    name: ${POSTGRES_DB}
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
