name: Execute all tests
on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  java-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew check
